#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = pkg.version;
const name = pkg.name;

const outPath = path.join(root, "src/cli/lib/version.gen.ts");
const content = `/** Generated by scripts/gen-version.mjs — do not edit */
export const CLI_VERSION = ${JSON.stringify(version)};
export const NPM_PACKAGE_NAME = ${JSON.stringify(name)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, "utf8");
